lucky_numbers = [4, 15, 8, 16, 23,42]
friends =["a", "b", "c", "d", "e"]
friends.append("f")
friends.extend(lucky_numbers)
friends.insert(2, "crazy")
friends.remove("c")
print(friends)
print(friends.index("b"))
friends.pop()
print(friends)
print(friends.count(4))
print(friends)
lucky_numbers.sort()
print(lucky_numbers)
lucky_numbers.reverse()
print(lucky_numbers)
friends2 = friends.copy()
print(friends2)
friends.clear()